env_name: "CartPole-v1"
policy_type: "ppo"
total_timesteps: 100000
num_seeds: 20
lr: 0.0003
gamma: 0.99

baseline_type: "vanilla_plus"
extra_capacity: 10000

device: "cpu"
log_dir: "results/baselines/vanilla_plus"
use_wandb: false
